# Generated by Django 4.0.3 on 2022-04-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
