# Generated by Django 4.0.3 on 2022-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('operational', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='electronics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='politics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sports',
        ),
    ]
