# Generated by Django 4.0.3 on 2022-04-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_preferences_remove_user_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='sources',
            field=models.TextField(null=True),
        ),
    ]
