# Generated by Django 4.0.3 on 2022-04-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_delete_news'),
        ('register', '0005_preferences_keywords_preferences_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
